import Link from "next/link";
import { ArrowRight, Check, Headphones, Users, WandSparkles } from "lucide-react";
import { JoinRoomForm } from "@/components/room/JoinRoomForm";
import { AppShell } from "@/components/ui/AppNav";
import { JamUnavailable } from "@/components/JamUnavailable";
import { CreateRoomButton } from "@/components/room/CreateRoomButton";
import { isSupabaseConfigured } from "@/lib/supabase/env";

export default function JamPage({ searchParams }: { searchParams?: { song?: string } }) {
  if (!isSupabaseConfigured()) return <JamUnavailable />;
  return <AppShell><main className="mx-auto min-h-full max-w-5xl px-4 py-5 sm:px-6 md:px-8 md:py-8 xl:px-10 xl:py-12">
    <header className="max-w-2xl"><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-jam">Jam together</p><h1 className="mt-1.5 font-display text-[30px] font-bold leading-[1.06] tracking-[-0.035em] sm:text-4xl">Get everyone on the same page.</h1><p className="mt-2 text-[13px] leading-relaxed text-text-muted sm:text-sm md:text-base">Join with a code or start a room for your band.</p></header>
    <section className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-[0.9fr_1.1fr]">
      <div className="rounded-2xl border border-jam/25 bg-jam/[0.05] p-4 sm:rounded-3xl sm:p-5 md:p-6 xl:p-7"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-jam/15 text-jam"><Users className="size-5" /></span><div><h2 className="font-display text-lg font-bold sm:text-xl">Join a room</h2><p className="text-xs text-text-muted">Enter the code from your host.</p></div></div><div className="mt-5"><JoinRoomForm /></div></div>
      <div className="rounded-2xl border border-line bg-bg-raised p-4 sm:rounded-3xl sm:p-5 md:p-6 xl:p-7"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-accent/15 text-accent"><WandSparkles className="size-5" /></span><div><h2 className="font-display text-lg font-bold sm:text-xl">Start a rehearsal</h2><p className="text-xs text-text-muted">Pick the music and invite your people.</p></div></div>{searchParams?.song ? <div className="mt-4 rounded-xl border border-jam/25 bg-jam/[0.06] px-3.5 py-3 text-xs text-jam">Your selected song will open with this room.</div> : null}<div className="mt-4 grid grid-cols-2 gap-2">{["Pick the music", "Assign roles", "Check audio", "Start playing"].map((step) => <div key={step} className="flex items-center gap-2 rounded-xl border border-line-soft bg-bg-card px-2.5 py-2.5 text-[12px] sm:px-3 sm:text-sm"><span className="flex size-5 shrink-0 items-center justify-center rounded-full bg-jam/15 text-jam"><Check className="size-3" /></span>{step}</div>)}</div><div className="mt-5 grid grid-cols-2 gap-2"><CreateRoomButton className="min-w-0" songId={searchParams?.song} /><Link href="/library" className="inline-flex h-11 items-center justify-center gap-2 rounded-xl border border-line px-3 text-[13px] font-semibold active:bg-bg-higher">Choose song <ArrowRight className="size-4" /></Link></div></div>
    </section>
    <section className="-mx-4 mt-4 flex snap-x gap-2.5 overflow-x-auto px-4 pb-1 sm:mx-0 sm:grid sm:grid-cols-3 sm:px-0"><div className="w-[72vw] max-w-[280px] shrink-0 snap-start rounded-2xl border border-line-soft bg-bg-card p-4 sm:w-auto sm:max-w-none"><Headphones className="size-4 text-jam" /><p className="mt-3 text-sm font-semibold">Your part, clearly</p><p className="mt-1 text-xs leading-relaxed text-text-muted">Shapes for guitar, roots for bass, entrances for vocals.</p></div><div className="w-[72vw] max-w-[280px] shrink-0 snap-start rounded-2xl border border-line-soft bg-bg-card p-4 sm:w-auto sm:max-w-none"><Users className="size-4 text-jam" /><p className="mt-3 text-sm font-semibold">See who is ready</p><p className="mt-1 text-xs leading-relaxed text-text-muted">Know everyone&apos;s role before the count-in.</p></div><div className="w-[72vw] max-w-[280px] shrink-0 snap-start rounded-2xl border border-line-soft bg-bg-card p-4 sm:w-auto sm:max-w-none"><WandSparkles className="size-4 text-jam" /><p className="mt-3 text-sm font-semibold">Loop the hard part</p><p className="mt-1 text-xs leading-relaxed text-text-muted">Rehearse one section without losing the room.</p></div></section>
  </main></AppShell>;
}
