import type { Visual } from "./types";

export const ABYSS_VISUALS: Record<string, Visual[]> = {
  "aby-jazz-harmony": [
    {
      type: "sequence",
      label: "ii-V-I with tensions: Dm9, G7b9, Cmaj9",
      instrument: "piano",
      bpm: 70,
      steps: [
        { notes: ["D3", "F4", "A4", "C5", "E5"], label: "ii9: Dm9", beats: 2 },
        { notes: ["G2", "F4", "Ab4", "B4"], label: "V7b9: G7b9", beats: 2 },
        { notes: ["C3", "E4", "G4", "B4", "D5"], label: "Imaj9: Cmaj9", beats: 4 },
      ],
    },
    {
      type: "piano",
      label: "G7alt: shell (3+7) plus b9, #9, b13",
      notes: ["G2", "B3", "F4", "Ab4", "Bb4", "Eb5"],
      roots: ["G2"],
    },
    {
      type: "guitar-chord",
      label: "G13 (gentle dominant)",
      frets: [3, null, 3, 4, 5, null],
      fingers: [1, null, 2, 3, 4, null],
    },
    {
      type: "guitar-chord",
      label: "G7#9 (altered heat)",
      baseFret: 9,
      frets: [null, 2, 1, 2, 3, null],
      fingers: [null, 2, 1, 3, 4, null],
    },
  ],

  "aby-reharm": [
    {
      type: "sequence",
      label: "Original: Dm7 G7 Cmaj7",
      instrument: "piano",
      bpm: 80,
      steps: [
        { notes: ["D3", "F3", "A3", "C4"], label: "ii: Dm7", beats: 2 },
        { notes: ["G2", "F3", "B3", "D4"], label: "V: G7", beats: 2 },
        { notes: ["C3", "E3", "G3", "B3"], label: "I: Cmaj7", beats: 4 },
      ],
    },
    {
      type: "sequence",
      label: "Tritone sub: Dm7 Db7 Cmaj7 (bass walks D-Db-C)",
      instrument: "piano",
      bpm: 80,
      steps: [
        { notes: ["D3", "F3", "A3", "C4"], label: "ii: Dm7", beats: 2 },
        { notes: ["Db3", "F3", "Ab3", "B3"], label: "bII7: Db7", beats: 2 },
        { notes: ["C3", "E3", "G3", "B3"], label: "I: Cmaj7", beats: 4 },
      ],
    },
    {
      type: "sequence",
      label: "Passing diminished: C to C#dim7 to Dm7",
      instrument: "piano",
      bpm: 80,
      steps: [
        { notes: ["C3", "E3", "G3", "C4"], label: "I: C", beats: 2 },
        { notes: ["C#3", "E3", "G3", "Bb3"], label: "#Idim7: C#dim7", beats: 2 },
        { notes: ["D3", "F3", "A3", "C4"], label: "ii: Dm7", beats: 2 },
        { notes: ["G2", "F3", "B3", "D4"], label: "V: G7", beats: 2 },
        { notes: ["C3", "E3", "G3", "B3"], label: "I: Cmaj7", beats: 4 },
      ],
    },
  ],

  "aby-rhythm-mastery": [
    {
      type: "sequence",
      label: "Straight eighths",
      instrument: "piano",
      bpm: 100,
      steps: [
        { notes: ["C4"], label: "straight", beats: 0.5 },
        { notes: ["D4"], beats: 0.5 },
        { notes: ["E4"], beats: 0.5 },
        { notes: ["G4"], beats: 0.5 },
        { notes: ["A4"], beats: 0.5 },
        { notes: ["G4"], beats: 0.5 },
        { notes: ["E4"], beats: 0.5 },
        { notes: ["D4"], beats: 0.5 },
        { notes: ["C4"], beats: 2 },
      ],
    },
    {
      type: "sequence",
      label: "Swing eighths (same notes, long-short)",
      instrument: "piano",
      bpm: 100,
      steps: [
        { notes: ["C4"], label: "swing", beats: 0.67 },
        { notes: ["D4"], beats: 0.33 },
        { notes: ["E4"], beats: 0.67 },
        { notes: ["G4"], beats: 0.33 },
        { notes: ["A4"], beats: 0.67 },
        { notes: ["G4"], beats: 0.33 },
        { notes: ["E4"], beats: 0.67 },
        { notes: ["D4"], beats: 0.33 },
        { notes: ["C4"], beats: 2 },
      ],
    },
    {
      type: "sequence",
      label: "7/8 pulse as 2+2+3 (TA-ka TA-ka TA-ki-ta)",
      instrument: "piano",
      bpm: 90,
      steps: [
        { notes: ["E4"], label: "TA", beats: 0.5 },
        { notes: ["C4"], label: "ka", beats: 0.5 },
        { notes: ["E4"], label: "TA", beats: 0.5 },
        { notes: ["C4"], label: "ka", beats: 0.5 },
        { notes: ["E4"], label: "TA", beats: 0.5 },
        { notes: ["C4"], label: "ki", beats: 0.5 },
        { notes: ["C4"], label: "ta", beats: 0.5 },
        { notes: ["E4"], label: "TA", beats: 0.5 },
        { notes: ["C4"], label: "ka", beats: 0.5 },
        { notes: ["E4"], label: "TA", beats: 0.5 },
        { notes: ["C4"], label: "ka", beats: 0.5 },
        { notes: ["E4"], label: "TA", beats: 0.5 },
        { notes: ["C4"], label: "ki", beats: 0.5 },
        { notes: ["C4"], label: "ta", beats: 0.5 },
      ],
    },
  ],

  "aby-ear-realtime": [
    {
      type: "sequence",
      label: "Ear test A: I-vi-ii-V",
      instrument: "piano",
      bpm: 90,
      steps: [
        { notes: ["C3", "E3", "G3", "C4"], label: "I", beats: 2 },
        { notes: ["A2", "C3", "E3", "A3"], label: "vi", beats: 2 },
        { notes: ["D3", "F3", "A3", "C4"], label: "ii", beats: 2 },
        { notes: ["G2", "F3", "B3", "D4"], label: "V", beats: 2 },
      ],
    },
    {
      type: "sequence",
      label: "Ear test B: I-IV-V",
      instrument: "piano",
      bpm: 90,
      steps: [
        { notes: ["C3", "E3", "G3", "C4"], label: "I", beats: 2 },
        { notes: ["F2", "F3", "A3", "C4"], label: "IV", beats: 2 },
        { notes: ["G2", "G3", "B3", "D4"], label: "V", beats: 2 },
        { notes: ["C3", "E3", "G3", "C4"], label: "I", beats: 2 },
      ],
    },
    {
      type: "sequence",
      label: "Follow the bass: falling fifths into home",
      instrument: "piano",
      bpm: 90,
      steps: [
        { notes: ["E3"], label: "iii", beats: 1 },
        { notes: ["A2"], label: "vi", beats: 1 },
        { notes: ["D3"], label: "ii", beats: 1 },
        { notes: ["G2"], label: "V", beats: 1 },
        { notes: ["C3"], label: "I", beats: 2 },
      ],
    },
  ],

  "aby-songwriting": [
    {
      type: "sequence",
      label: "Verse: low register, sparse",
      instrument: "piano",
      bpm: 90,
      steps: [
        { notes: ["A2", "C3", "E3"], label: "vi: Am", beats: 2 },
        { notes: ["F2", "A2", "C3"], label: "IV: F", beats: 2 },
        { notes: ["G2", "B2", "D3"], label: "V: G", beats: 2 },
        { notes: ["A2", "C3", "E3"], label: "vi: Am", beats: 2 },
      ],
    },
    {
      type: "sequence",
      label: "Chorus: lifted register, fuller",
      instrument: "piano",
      bpm: 90,
      steps: [
        { notes: ["C3", "E4", "G4", "C5"], label: "I: C", beats: 2 },
        { notes: ["F3", "F4", "A4", "C5"], label: "IV: F", beats: 2 },
        { notes: ["G3", "G4", "B4", "D5"], label: "V: G", beats: 2 },
        { notes: ["C3", "E4", "G4", "C5"], label: "I: C", beats: 2 },
      ],
    },
  ],

  "aby-gtr-chord-melody": [
    {
      type: "guitar-chord",
      label: "Cmaj7 - melody E on top",
      frets: [null, 3, 2, 0, 0, 0],
      fingers: [null, 3, 2, null, null, null],
    },
    {
      type: "guitar-chord",
      label: "Cmaj7 - melody G on top",
      baseFret: 3,
      frets: [null, 1, 3, 2, 3, 1],
      fingers: [null, 1, 3, 2, 4, 1],
    },
    {
      type: "guitar-chord",
      label: "Cmaj7/G - melody B on top",
      baseFret: 5,
      frets: [null, null, 1, 1, 1, 3],
      fingers: [null, null, 1, 1, 1, 3],
    },
    {
      type: "sequence",
      label: "Chord-melody phrase: chords on strong beats, melody rides",
      instrument: "guitar",
      bpm: 80,
      steps: [
        { notes: ["C3", "G3", "B3", "E4"], label: "Cmaj7 (E top)", beats: 2 },
        { notes: ["D4"], beats: 0.5 },
        { notes: ["E4"], beats: 0.5 },
        { notes: ["A2", "G3", "C4", "E4"], label: "Am7", beats: 2 },
        { notes: ["D4"], beats: 0.5 },
        { notes: ["C4"], beats: 0.5 },
        { notes: ["D3", "A3", "C4", "F4"], label: "Dm7 (F top)", beats: 2 },
        { notes: ["G2", "F3", "B3", "D4"], label: "G7", beats: 2 },
        { notes: ["C3", "G3", "B3", "E4"], label: "Cmaj7", beats: 4 },
      ],
    },
  ],

  "aby-gtr-advanced-tech": [
    {
      type: "sequence",
      label: "Am sweep arpeggio, up and back",
      instrument: "guitar",
      bpm: 180,
      steps: [
        { notes: ["A3"], label: "sweep down-stroke", beats: 0.5 },
        { notes: ["C4"], beats: 0.5 },
        { notes: ["E4"], beats: 0.5 },
        { notes: ["A4"], beats: 0.5 },
        { notes: ["C5"], beats: 0.5 },
        { notes: ["E5"], label: "turn", beats: 0.5 },
        { notes: ["C5"], label: "drag back up", beats: 0.5 },
        { notes: ["A4"], beats: 0.5 },
        { notes: ["E4"], beats: 0.5 },
        { notes: ["C4"], beats: 0.5 },
        { notes: ["A3"], beats: 1 },
      ],
    },
    {
      type: "fretboard",
      label: "Three-string Am sweep shape at the 12th position",
      startFret: 11,
      fretCount: 4,
      notes: [
        { string: 3, fret: 14, label: "A", root: true },
        { string: 2, fret: 13, label: "C" },
        { string: 1, fret: 12, label: "E" },
      ],
    },
    {
      type: "sequence",
      label: "Tap figure on the B string: tap 12, pull to 5, hammer 8",
      instrument: "guitar",
      bpm: 120,
      steps: [
        { notes: ["B4"], label: "tap 12", beats: 0.33 },
        { notes: ["E4"], label: "pull 5", beats: 0.33 },
        { notes: ["G4"], label: "hammer 8", beats: 0.34 },
        { notes: ["B4"], label: "tap", beats: 0.33 },
        { notes: ["E4"], beats: 0.33 },
        { notes: ["G4"], beats: 0.34 },
        { notes: ["B4"], label: "tap", beats: 0.33 },
        { notes: ["E4"], beats: 0.33 },
        { notes: ["G4"], beats: 0.34 },
        { notes: ["B4"], beats: 1 },
      ],
    },
  ],

  "aby-gtr-jazz-vocab": [
    {
      type: "sequence",
      label: "Guide tones: 3rds and 7ths through ii-V-I",
      instrument: "guitar",
      bpm: 80,
      steps: [
        { notes: ["F3", "C4"], label: "Dm7: 3+7", beats: 2 },
        { notes: ["F3", "B3"], label: "G7: 7+3", beats: 2 },
        { notes: ["E3", "B3"], label: "Cmaj7: 3+7", beats: 4 },
      ],
    },
    {
      type: "sequence",
      label: "Enclosure over G7 landing on E, the 3rd of Cmaj7",
      instrument: "guitar",
      bpm: 110,
      steps: [
        { notes: ["G3"], label: "G7 arpeggio", beats: 0.5 },
        { notes: ["B3"], beats: 0.5 },
        { notes: ["D4"], beats: 0.5 },
        { notes: ["F4"], label: "above the target", beats: 0.5 },
        { notes: ["D#4"], label: "below the target", beats: 0.5 },
        { notes: ["E4"], label: "lands: 3rd of C", beats: 0.5 },
        { notes: ["C3", "G3", "B3", "E4"], label: "Cmaj7", beats: 3 },
      ],
    },
    {
      type: "sequence",
      label: "G bebop scale descending: chord tones on downbeats",
      instrument: "guitar",
      bpm: 110,
      steps: [
        { notes: ["G4"], label: "R", beats: 0.5 },
        { notes: ["F#4"], label: "passing", beats: 0.5 },
        { notes: ["F4"], label: "b7", beats: 0.5 },
        { notes: ["E4"], beats: 0.5 },
        { notes: ["D4"], label: "5", beats: 0.5 },
        { notes: ["C4"], beats: 0.5 },
        { notes: ["B3"], label: "3", beats: 0.5 },
        { notes: ["A3"], beats: 0.5 },
        { notes: ["G3"], label: "R", beats: 2 },
      ],
    },
  ],

  "aby-pno-rootless": [
    {
      type: "piano",
      label: "Dm7 A-form rootless: F A C E (3-5-7-9)",
      notes: ["F3", "A3", "C4", "E4"],
    },
    {
      type: "piano",
      label: "G7 A-form rootless: F A B E (7-9-3-13)",
      notes: ["F3", "A3", "B3", "E4"],
    },
    {
      type: "piano",
      label: "Cmaj7 A-form rootless: E G B D (3-5-7-9)",
      notes: ["E3", "G3", "B3", "D4"],
    },
    {
      type: "sequence",
      label: "Comping the ii-V-I: each finger moves a step or less",
      instrument: "piano",
      bpm: 80,
      steps: [
        { notes: ["F3", "A3", "C4", "E4"], label: "ii: Dm7", beats: 2 },
        { notes: ["F3", "A3", "B3", "E4"], label: "V: G7", beats: 2 },
        { notes: ["E3", "G3", "B3", "D4"], label: "I: Cmaj7", beats: 4 },
      ],
    },
  ],

  "aby-pno-stride": [
    {
      type: "sequence",
      label: "Stride pattern: bass on 1 and 3, chord on 2 and 4",
      instrument: "piano",
      bpm: 100,
      steps: [
        { notes: ["C2"], label: "1: root", beats: 1 },
        { notes: ["E3", "G3", "C4"], label: "2: chord", beats: 1 },
        { notes: ["G2"], label: "3: fifth", beats: 1 },
        { notes: ["E3", "G3", "C4"], label: "4: chord", beats: 1 },
        { notes: ["G2"], label: "1: G7", beats: 1 },
        { notes: ["F3", "B3", "D4"], beats: 1 },
        { notes: ["D2"], label: "3: fifth", beats: 1 },
        { notes: ["F3", "B3", "D4"], beats: 1 },
        { notes: ["C2", "E3", "G3", "C4"], label: "home", beats: 2 },
      ],
    },
    {
      type: "sequence",
      label: "Walking bass over Dm7 G7 C, half-step into each root",
      instrument: "piano",
      bpm: 110,
      steps: [
        { notes: ["D2"], label: "Dm7", beats: 1 },
        { notes: ["F2"], beats: 1 },
        { notes: ["A2"], beats: 1 },
        { notes: ["B2"], beats: 1 },
        { notes: ["G2"], label: "G7", beats: 1 },
        { notes: ["A2"], beats: 1 },
        { notes: ["B2"], beats: 1 },
        { notes: ["Db3"], label: "half step above", beats: 1 },
        { notes: ["C3"], label: "C", beats: 4 },
      ],
    },
  ],

  "aby-pno-solo-arranging": [
    {
      type: "sequence",
      label: "Intro vamp: Imaj7 to bIImaj7",
      instrument: "piano",
      bpm: 80,
      steps: [
        { notes: ["C3", "E3", "G3", "B3"], label: "Imaj7", beats: 2 },
        { notes: ["Db3", "F3", "Ab3", "C4"], label: "bIImaj7", beats: 2 },
        { notes: ["C3", "E3", "G3", "B3"], label: "Imaj7", beats: 2 },
        { notes: ["Db3", "F3", "Ab3", "C4"], label: "bIImaj7", beats: 2 },
        { notes: ["C3", "E3", "G3", "B3"], label: "and in...", beats: 4 },
      ],
    },
    {
      type: "sequence",
      label: "Reharm under a held melody note: floor moves, tune stays",
      instrument: "piano",
      bpm: 70,
      steps: [
        { notes: ["C3", "E3", "G3", "C5"], label: "I, melody on C", beats: 2 },
        { notes: ["Db3", "F3", "Ab3", "C5"], label: "bIImaj7 under the same C", beats: 2 },
        { notes: ["C3", "G3", "E4", "C5"], label: "home", beats: 4 },
      ],
    },
    {
      type: "piano",
      label: "Ending color: Cmaj7 with 9 and #11 ringing",
      notes: ["C3", "E3", "G3", "B3", "D4", "F#4"],
      roots: ["C3"],
    },
  ],
};
