import type { Visual } from "./types";

export const BELOW_VISUALS: Record<string, Visual[]> = {
  "blw-circle-of-fifths": [
    {
      type: "sequence",
      label: "Clockwise: the sharp side (up in fifths)",
      instrument: "piano",
      bpm: 80,
      steps: [
        { notes: ["C4"], label: "C (0 sharps)" },
        { notes: ["G4"], label: "G (1)" },
        { notes: ["D4"], label: "D (2)" },
        { notes: ["A4"], label: "A (3)" },
        { notes: ["E4"], label: "E (4)" },
        { notes: ["B4"], label: "B (5)" },
        { notes: ["F#4"], label: "F# (6)" },
      ],
    },
    {
      type: "sequence",
      label: "Counterclockwise: the flat side (down in fifths)",
      instrument: "piano",
      bpm: 80,
      steps: [
        { notes: ["C4"], label: "C (0 flats)" },
        { notes: ["F4"], label: "F (1)" },
        { notes: ["Bb4"], label: "Bb (2)" },
        { notes: ["Eb4"], label: "Eb (3)" },
        { notes: ["Ab4"], label: "Ab (4)" },
        { notes: ["Db4"], label: "Db (5)" },
        { notes: ["Gb4"], label: "Gb (6)" },
      ],
    },
    {
      type: "sequence",
      label: "Neighbors on the circle: G major's chord family",
      instrument: "piano",
      bpm: 70,
      steps: [
        { notes: ["G3", "B3", "D4"], label: "I: G", beats: 2 },
        { notes: ["C4", "E4", "G4"], label: "IV: C", beats: 2 },
        { notes: ["D4", "F#4", "A4"], label: "V: D", beats: 2 },
        { notes: ["E4", "G4", "B4"], label: "vi: Em", beats: 2 },
        { notes: ["G3", "B3", "D4"], label: "I: G", beats: 2 },
      ],
    },
  ],

  "blw-diatonic-chords": [
    {
      type: "sequence",
      label: "The seven diatonic chords of C major",
      instrument: "piano",
      bpm: 70,
      steps: [
        { notes: ["C4", "E4", "G4"], label: "I: C", beats: 2 },
        { notes: ["D4", "F4", "A4"], label: "ii: Dm", beats: 2 },
        { notes: ["E4", "G4", "B4"], label: "iii: Em", beats: 2 },
        { notes: ["F4", "A4", "C5"], label: "IV: F", beats: 2 },
        { notes: ["G4", "B4", "D5"], label: "V: G", beats: 2 },
        { notes: ["A4", "C5", "E5"], label: "vi: Am", beats: 2 },
        { notes: ["B4", "D5", "F5"], label: "vii(dim): Bdim", beats: 2 },
        { notes: ["C5", "E5", "G5"], label: "I: C", beats: 2 },
      ],
    },
    {
      type: "sequence",
      label: "Same numerals, new key: the chords of G major",
      instrument: "piano",
      bpm: 70,
      steps: [
        { notes: ["G3", "B3", "D4"], label: "I: G", beats: 2 },
        { notes: ["A3", "C4", "E4"], label: "ii: Am", beats: 2 },
        { notes: ["B3", "D4", "F#4"], label: "iii: Bm", beats: 2 },
        { notes: ["C4", "E4", "G4"], label: "IV: C", beats: 2 },
        { notes: ["D4", "F#4", "A4"], label: "V: D", beats: 2 },
        { notes: ["E4", "G4", "B4"], label: "vi: Em", beats: 2 },
        { notes: ["F#4", "A4", "C5"], label: "vii(dim): F#dim", beats: 2 },
        { notes: ["G4", "B4", "D5"], label: "I: G", beats: 2 },
      ],
    },
  ],

  "blw-progressions": [
    {
      type: "sequence",
      label: "I-V-vi-IV in C: the pop workhorse",
      instrument: "piano",
      bpm: 90,
      steps: [
        { notes: ["C4", "E4", "G4"], label: "I: C", beats: 4 },
        { notes: ["G3", "B3", "D4"], label: "V: G", beats: 4 },
        { notes: ["A3", "C4", "E4"], label: "vi: Am", beats: 4 },
        { notes: ["F3", "A3", "C4"], label: "IV: F", beats: 4 },
      ],
    },
    {
      type: "sequence",
      label: "ii-V-I in C: the jazz engine",
      instrument: "piano",
      bpm: 80,
      steps: [
        { notes: ["D4", "F4", "A4", "C5"], label: "ii: Dm7", beats: 2 },
        { notes: ["G3", "B3", "D4", "F4"], label: "V: G7", beats: 2 },
        { notes: ["C4", "E4", "G4", "B4"], label: "I: Cmaj7", beats: 4 },
      ],
    },
    {
      type: "sequence",
      label: "12-bar blues in A (one chord per bar)",
      instrument: "piano",
      bpm: 120,
      steps: [
        { notes: ["A3", "C#4", "E4", "G4"], label: "Bar 1: A7", beats: 4 },
        { notes: ["A3", "C#4", "E4", "G4"], label: "Bar 2: A7", beats: 4 },
        { notes: ["A3", "C#4", "E4", "G4"], label: "Bar 3: A7", beats: 4 },
        { notes: ["A3", "C#4", "E4", "G4"], label: "Bar 4: A7", beats: 4 },
        { notes: ["D3", "F#3", "A3", "C4"], label: "Bar 5: D7", beats: 4 },
        { notes: ["D3", "F#3", "A3", "C4"], label: "Bar 6: D7", beats: 4 },
        { notes: ["A3", "C#4", "E4", "G4"], label: "Bar 7: A7", beats: 4 },
        { notes: ["A3", "C#4", "E4", "G4"], label: "Bar 8: A7", beats: 4 },
        { notes: ["E3", "G#3", "B3", "D4"], label: "Bar 9: E7", beats: 4 },
        { notes: ["D3", "F#3", "A3", "C4"], label: "Bar 10: D7", beats: 4 },
        { notes: ["A3", "C#4", "E4", "G4"], label: "Bar 11: A7", beats: 4 },
        { notes: ["E3", "G#3", "B3", "D4"], label: "Bar 12: E7 (turnaround)", beats: 4 },
      ],
    },
  ],

  "blw-seventh-chords": [
    {
      type: "piano",
      label: "Cmaj7: C-E-G-B, dreamy and soft",
      notes: ["C4", "E4", "G4", "B4"],
      roots: ["C4"],
    },
    {
      type: "piano",
      label: "C7 (dominant): C-E-G-Bb, bluesy and tense",
      notes: ["C4", "E4", "G4", "Bb4"],
      roots: ["C4"],
    },
    {
      type: "piano",
      label: "Cm7: C-Eb-G-Bb, mellow and smooth",
      notes: ["C4", "Eb4", "G4", "Bb4"],
      roots: ["C4"],
    },
    {
      type: "sequence",
      label: "The three flavors side by side",
      instrument: "piano",
      bpm: 60,
      steps: [
        { notes: ["C4", "E4", "G4", "B4"], label: "Cmaj7", beats: 2 },
        { notes: ["C4", "E4", "G4", "Bb4"], label: "C7", beats: 2 },
        { notes: ["C4", "Eb4", "G4", "Bb4"], label: "Cm7", beats: 2 },
      ],
    },
  ],

  "blw-ear-basics": [
    {
      type: "sequence",
      label: "Major vs minor: hear the third move",
      instrument: "piano",
      bpm: 60,
      steps: [
        { notes: ["C4", "E4", "G4"], label: "C major", beats: 2 },
        { notes: ["C4", "Eb4", "G4"], label: "C minor", beats: 2 },
        { notes: ["A3", "C#4", "E4"], label: "A major", beats: 2 },
        { notes: ["A3", "C4", "E4"], label: "A minor", beats: 2 },
      ],
    },
    {
      type: "sequence",
      label: "Interval anchors from C",
      instrument: "piano",
      bpm: 80,
      steps: [
        { notes: ["C4"], label: "C" },
        { notes: ["Eb4"], label: "m3: Greensleeves" },
        { notes: ["C4"], label: "C" },
        { notes: ["E4"], label: "M3: Saints" },
        { notes: ["C4"], label: "C" },
        { notes: ["F4"], label: "P4: Bride" },
        { notes: ["C4"], label: "C" },
        { notes: ["G4"], label: "P5: Star Wars" },
        { notes: ["C4"], label: "C" },
        { notes: ["C5"], label: "Octave: Rainbow", beats: 2 },
      ],
    },
  ],

  "blw-gtr-barre": [
    {
      type: "guitar-chord",
      label: "F major (E-shape barre)",
      frets: [1, 3, 3, 2, 1, 1],
      fingers: [1, 3, 4, 2, 1, 1],
      baseFret: 1,
    },
    {
      type: "guitar-chord",
      label: "B major (A-shape barre)",
      frets: [null, 2, 4, 4, 4, 2],
      fingers: [null, 1, 2, 3, 4, 1],
      baseFret: 1,
    },
    {
      type: "guitar-chord",
      label: "B minor (A-shape minor barre)",
      frets: [null, 2, 4, 4, 3, 2],
      fingers: [null, 1, 3, 4, 2, 1],
      baseFret: 1,
    },
    {
      type: "guitar-chord",
      label: "C major (E-shape barre at fret 8)",
      frets: [1, 3, 3, 2, 1, 1],
      fingers: [1, 3, 4, 2, 1, 1],
      baseFret: 8,
    },
  ],

  "blw-gtr-power-chords": [
    {
      type: "guitar-chord",
      label: "E5",
      frets: [0, 2, 2, null, null, null],
      fingers: [null, 3, 4, null, null, null],
    },
    {
      type: "guitar-chord",
      label: "A5",
      frets: [null, 0, 2, 2, null, null],
      fingers: [null, null, 3, 4, null, null],
    },
    {
      type: "guitar-chord",
      label: "G5 (movable shape, root fret 3)",
      frets: [3, 5, 5, null, null, null],
      fingers: [1, 3, 4, null, null, null],
    },
    {
      type: "sequence",
      label: "G5 - F5 - C5 riff (verse muted, chorus open)",
      instrument: "guitar",
      bpm: 100,
      steps: [
        { notes: ["G2", "D3", "G3"], label: "G5", beats: 2 },
        { notes: ["G2", "D3", "G3"], beats: 2 },
        { notes: ["F2", "C3", "F3"], label: "F5", beats: 2 },
        { notes: ["F2", "C3", "F3"], beats: 2 },
        { notes: ["C3", "G3", "C4"], label: "C5", beats: 2 },
        { notes: ["C3", "G3", "C4"], beats: 2 },
        { notes: ["G2", "D3", "G3"], label: "G5", beats: 4 },
      ],
    },
  ],

  "blw-gtr-pentatonic": [
    {
      type: "fretboard",
      label: "A minor pentatonic, box 1 (5th position)",
      startFret: 4,
      fretCount: 6,
      notes: [
        { string: 6, fret: 5, label: "A", root: true },
        { string: 6, fret: 8, label: "C" },
        { string: 5, fret: 5, label: "D" },
        { string: 5, fret: 7, label: "E" },
        { string: 4, fret: 5, label: "G" },
        { string: 4, fret: 7, label: "A", root: true },
        { string: 3, fret: 5, label: "C" },
        { string: 3, fret: 7, label: "D" },
        { string: 2, fret: 5, label: "E" },
        { string: 2, fret: 8, label: "G" },
        { string: 1, fret: 5, label: "A", root: true },
        { string: 1, fret: 8, label: "C" },
      ],
    },
    {
      type: "fretboard",
      label: "Add the blues note (b5, Eb) as passing spice",
      startFret: 4,
      fretCount: 6,
      notes: [
        { string: 6, fret: 5, label: "A", root: true },
        { string: 6, fret: 8, label: "C" },
        { string: 5, fret: 5, label: "D" },
        { string: 5, fret: 6, label: "Eb" },
        { string: 5, fret: 7, label: "E" },
        { string: 4, fret: 5, label: "G" },
        { string: 4, fret: 7, label: "A", root: true },
        { string: 3, fret: 5, label: "C" },
        { string: 3, fret: 7, label: "D" },
        { string: 3, fret: 8, label: "Eb" },
        { string: 2, fret: 5, label: "E" },
        { string: 2, fret: 8, label: "G" },
        { string: 1, fret: 5, label: "A", root: true },
        { string: 1, fret: 8, label: "C" },
      ],
    },
    {
      type: "sequence",
      label: "Box 1 ascending: A C D E G A C D E G A C",
      instrument: "guitar",
      bpm: 80,
      steps: [
        { notes: ["A2"], label: "A" },
        { notes: ["C3"], label: "C" },
        { notes: ["D3"], label: "D" },
        { notes: ["E3"], label: "E" },
        { notes: ["G3"], label: "G" },
        { notes: ["A3"], label: "A" },
        { notes: ["C4"], label: "C" },
        { notes: ["D4"], label: "D" },
        { notes: ["E4"], label: "E" },
        { notes: ["G4"], label: "G" },
        { notes: ["A4"], label: "A" },
        { notes: ["C5"], label: "C", beats: 2 },
      ],
    },
  ],

  "blw-gtr-legato": [
    {
      type: "sequence",
      label: "Trill on the G string: 5h7p5h7p5",
      instrument: "guitar",
      bpm: 90,
      steps: [
        { notes: ["C4"], label: "pick 5" },
        { notes: ["D4"], label: "h7" },
        { notes: ["C4"], label: "p5" },
        { notes: ["D4"], label: "h7" },
        { notes: ["C4"], label: "p5", beats: 2 },
      ],
    },
    {
      type: "sequence",
      label: "Combo lick in A minor pentatonic: hammer, slide, pull-off",
      instrument: "guitar",
      bpm: 70,
      steps: [
        { notes: ["G3"], label: "D str: 5" },
        { notes: ["A3"], label: "h7" },
        { notes: ["C4"], label: "G str: 5" },
        { notes: ["D4"], label: "h7" },
        { notes: ["E4"], label: "slide 7-9" },
        { notes: ["G4"], label: "B str: 8" },
        { notes: ["E4"], label: "p5", beats: 2 },
      ],
    },
  ],

  "blw-pno-inversions": [
    {
      type: "piano",
      label: "C major, root position: C-E-G (fingers 1-3-5)",
      notes: ["C4", "E4", "G4"],
      roots: ["C4"],
    },
    {
      type: "piano",
      label: "First inversion: E-G-C (fingers 1-2-5)",
      notes: ["E4", "G4", "C5"],
      roots: ["C5"],
    },
    {
      type: "piano",
      label: "Second inversion: G-C-E (fingers 1-3-5)",
      notes: ["G4", "C5", "E5"],
      roots: ["C5"],
    },
    {
      type: "sequence",
      label: "Voice-led I-IV-V-I in C: hand stays in one span",
      instrument: "piano",
      bpm: 60,
      steps: [
        { notes: ["C4", "E4", "G4"], label: "I: C", beats: 2 },
        { notes: ["C4", "F4", "A4"], label: "IV: F/C", beats: 2 },
        { notes: ["B3", "D4", "G4"], label: "V: G/B", beats: 2 },
        { notes: ["C4", "E4", "G4"], label: "I: C", beats: 2 },
      ],
    },
  ],

  "blw-pno-pedal": [
    {
      type: "sequence",
      label: "Replant drill: same chord, change the pedal on landing",
      instrument: "piano",
      bpm: 60,
      steps: [
        { notes: ["C3", "E3", "G3"], label: "play... pedal", beats: 4 },
        { notes: ["C3", "E3", "G3"], label: "play-lift... pedal", beats: 4 },
        { notes: ["C3", "E3", "G3"], label: "play-lift... pedal", beats: 4 },
        { notes: ["C3", "E3", "G3"], label: "play-lift... pedal", beats: 4 },
      ],
    },
    {
      type: "sequence",
      label: "Legato pedaling through C-F-G-C, whole notes",
      instrument: "piano",
      bpm: 60,
      steps: [
        { notes: ["C3", "E3", "G3"], label: "C: pedal down", beats: 4 },
        { notes: ["C3", "F3", "A3"], label: "F: lift-press", beats: 4 },
        { notes: ["B2", "D3", "G3"], label: "G: lift-press", beats: 4 },
        { notes: ["C3", "E3", "G3"], label: "C: lift-press", beats: 4 },
      ],
    },
  ],

  "blw-pno-arpeggios": [
    {
      type: "sequence",
      label: "Alberti bass through C-Am-F-G (low-high-middle-high)",
      instrument: "piano",
      bpm: 80,
      steps: [
        { notes: ["C3"], label: "C" },
        { notes: ["G3"] },
        { notes: ["E3"] },
        { notes: ["G3"] },
        { notes: ["A2"], label: "Am" },
        { notes: ["E3"] },
        { notes: ["C3"] },
        { notes: ["E3"] },
        { notes: ["F2"], label: "F" },
        { notes: ["C3"] },
        { notes: ["A2"] },
        { notes: ["C3"] },
        { notes: ["G2"], label: "G" },
        { notes: ["D3"] },
        { notes: ["B2"] },
        { notes: ["D3"] },
      ],
    },
    {
      type: "sequence",
      label: "Root-fifth-tenth: the ballad stretch (let the pedal hold it)",
      instrument: "piano",
      bpm: 70,
      steps: [
        { notes: ["C2"], label: "C: 1" },
        { notes: ["G2"], label: "5" },
        { notes: ["E3"], label: "10", beats: 2 },
        { notes: ["F2"], label: "F: 1" },
        { notes: ["C3"], label: "5" },
        { notes: ["A3"], label: "10", beats: 2 },
        { notes: ["G2"], label: "G: 1" },
        { notes: ["D3"], label: "5" },
        { notes: ["B3"], label: "10", beats: 2 },
        { notes: ["C2", "G2", "E3"], label: "C", beats: 4 },
      ],
    },
  ],

  "blw-pno-all-scales": [
    {
      type: "sequence",
      label: "C major, right hand: the standard fingering skeleton",
      instrument: "piano",
      bpm: 70,
      steps: [
        { notes: ["C4"], label: "1" },
        { notes: ["D4"], label: "2" },
        { notes: ["E4"], label: "3" },
        { notes: ["F4"], label: "1 (thumb under)" },
        { notes: ["G4"], label: "2" },
        { notes: ["A4"], label: "3" },
        { notes: ["B4"], label: "4" },
        { notes: ["C5"], label: "5", beats: 2 },
      ],
    },
    {
      type: "sequence",
      label: "F major, right hand: the exception (thumb avoids Bb)",
      instrument: "piano",
      bpm: 70,
      steps: [
        { notes: ["F4"], label: "1" },
        { notes: ["G4"], label: "2" },
        { notes: ["A4"], label: "3" },
        { notes: ["Bb4"], label: "4" },
        { notes: ["C5"], label: "1 (thumb under)" },
        { notes: ["D5"], label: "2" },
        { notes: ["E5"], label: "3" },
        { notes: ["F5"], label: "4", beats: 2 },
      ],
    },
    {
      type: "sequence",
      label: "B major, right hand: long fingers on the black keys",
      instrument: "piano",
      bpm: 70,
      steps: [
        { notes: ["B3"], label: "1" },
        { notes: ["C#4"], label: "2" },
        { notes: ["D#4"], label: "3" },
        { notes: ["E4"], label: "1 (thumb under)" },
        { notes: ["F#4"], label: "2" },
        { notes: ["G#4"], label: "3" },
        { notes: ["A#4"], label: "4" },
        { notes: ["B4"], label: "5", beats: 2 },
      ],
    },
  ],
};
