import type { Visual } from "./types";

/**
 * Interactive visuals for the "Shallow Waters" tier (depth 2).
 * Keyed by topic id from curriculum.ts.
 */
export const SHALLOWS_VISUALS: Record<string, Visual[]> = {
  "shw-major-scale": [
    {
      type: "piano",
      label: "C major scale - all white keys",
      notes: ["C4", "D4", "E4", "F4", "G4", "A4", "B4", "C5"],
      roots: ["C4", "C5"],
    },
    {
      type: "sequence",
      label: "The formula: W-W-H-W-W-W-H",
      instrument: "piano",
      bpm: 80,
      steps: [
        { notes: ["C4"], label: "root" },
        { notes: ["D4"], label: "W" },
        { notes: ["E4"], label: "W" },
        { notes: ["F4"], label: "H" },
        { notes: ["G4"], label: "W" },
        { notes: ["A4"], label: "W" },
        { notes: ["B4"], label: "W" },
        { notes: ["C5"], label: "H" },
      ],
    },
    {
      type: "sequence",
      label: "G major - the formula forces an F#",
      instrument: "piano",
      bpm: 80,
      steps: [
        { notes: ["G3"], label: "G" },
        { notes: ["A3"], label: "A" },
        { notes: ["B3"], label: "B" },
        { notes: ["C4"], label: "C" },
        { notes: ["D4"], label: "D" },
        { notes: ["E4"], label: "E" },
        { notes: ["F#4"], label: "F#" },
        { notes: ["G4"], label: "G" },
      ],
    },
    {
      type: "sequence",
      label: "C major scale on guitar",
      instrument: "guitar",
      bpm: 80,
      steps: [
        { notes: ["C3"], label: "C" },
        { notes: ["D3"], label: "D" },
        { notes: ["E3"], label: "E" },
        { notes: ["F3"], label: "F" },
        { notes: ["G3"], label: "G" },
        { notes: ["A3"], label: "A" },
        { notes: ["B3"], label: "B" },
        { notes: ["C4"], label: "C" },
      ],
    },
  ],

  "shw-keys": [
    {
      type: "piano",
      label: "Key of G - one sharp (F#)",
      notes: ["G3", "A3", "B3", "C4", "D4", "E4", "F#4", "G4"],
      roots: ["G3", "G4"],
    },
    {
      type: "piano",
      label: "Key of F - one flat (Bb)",
      notes: ["F3", "G3", "A3", "Bb3", "C4", "D4", "E4", "F4"],
      roots: ["F3", "F4"],
    },
    {
      type: "sequence",
      label: "Scale, then the chord that feels like home",
      instrument: "piano",
      bpm: 90,
      steps: [
        { notes: ["G3"], label: "G" },
        { notes: ["A3"], label: "A" },
        { notes: ["B3"], label: "B" },
        { notes: ["C4"], label: "C" },
        { notes: ["D4"], label: "D" },
        { notes: ["E4"], label: "E" },
        { notes: ["F#4"], label: "F#" },
        { notes: ["G4"], label: "G" },
        { notes: ["G3", "B3", "D4"], label: "G (home)", beats: 4 },
      ],
    },
  ],

  "shw-intervals": [
    {
      type: "sequence",
      label: "Interval pairs from C - melodic",
      instrument: "piano",
      bpm: 80,
      steps: [
        { notes: ["C4"], label: "C" },
        { notes: ["Eb4"], label: "m3" },
        { notes: ["C4"], label: "C" },
        { notes: ["E4"], label: "M3" },
        { notes: ["C4"], label: "C" },
        { notes: ["F4"], label: "P4" },
        { notes: ["C4"], label: "C" },
        { notes: ["G4"], label: "P5" },
        { notes: ["C4"], label: "C" },
        { notes: ["C5"], label: "P8" },
      ],
    },
    {
      type: "sequence",
      label: "Same intervals sounded together",
      instrument: "piano",
      bpm: 60,
      steps: [
        { notes: ["C4", "Eb4"], label: "m3", beats: 2 },
        { notes: ["C4", "E4"], label: "M3", beats: 2 },
        { notes: ["C4", "F4"], label: "P4", beats: 2 },
        { notes: ["C4", "G4"], label: "P5", beats: 2 },
        { notes: ["C4", "C5"], label: "P8", beats: 2 },
      ],
    },
    {
      type: "fretboard",
      label: "Intervals up the A string",
      notes: [
        { string: 5, fret: 0, label: "A", root: true },
        { string: 5, fret: 3, label: "m3" },
        { string: 5, fret: 4, label: "M3" },
        { string: 5, fret: 5, label: "P4" },
        { string: 5, fret: 7, label: "P5" },
        { string: 5, fret: 12, label: "P8" },
      ],
      startFret: 0,
      fretCount: 12,
    },
  ],

  "shw-minor-chords": [
    {
      type: "guitar-chord",
      label: "E major",
      frets: [0, 2, 2, 1, 0, 0],
      fingers: [null, 2, 3, 1, null, null],
    },
    {
      type: "guitar-chord",
      label: "E minor - lift one finger, the 3rd drops",
      frets: [0, 2, 2, 0, 0, 0],
      fingers: [null, 2, 3, null, null, null],
    },
    {
      type: "sequence",
      label: "C major vs C minor - one note moves",
      instrument: "piano",
      bpm: 70,
      steps: [
        { notes: ["C4", "E4", "G4"], label: "C", beats: 2 },
        { notes: ["C4", "Eb4", "G4"], label: "Cm", beats: 2 },
        { notes: ["C4", "E4", "G4"], label: "C", beats: 2 },
        { notes: ["C4", "Eb4", "G4"], label: "Cm", beats: 2 },
      ],
    },
    {
      type: "sequence",
      label: "Relative pair: C major and A minor share notes",
      instrument: "piano",
      bpm: 70,
      steps: [
        { notes: ["C4", "E4", "G4"], label: "C", beats: 2 },
        { notes: ["A3", "C4", "E4"], label: "Am", beats: 2 },
        { notes: ["C4", "E4", "G4"], label: "C", beats: 2 },
        { notes: ["A3", "C4", "E4"], label: "Am", beats: 2 },
      ],
    },
  ],

  "shw-gtr-minor-7th-chords": [
    {
      type: "guitar-chord",
      label: "Em",
      frets: [0, 2, 2, 0, 0, 0],
      fingers: [null, 2, 3, null, null, null],
    },
    {
      type: "guitar-chord",
      label: "Am",
      frets: [null, 0, 2, 2, 1, 0],
      fingers: [null, null, 2, 3, 1, null],
    },
    {
      type: "guitar-chord",
      label: "Dm",
      frets: [null, null, 0, 2, 3, 1],
      fingers: [null, null, null, 2, 3, 1],
    },
    {
      type: "sequence",
      label: "The dominant pull: 7th chords resolve",
      instrument: "guitar",
      bpm: 70,
      steps: [
        { notes: ["E2", "B2", "D3", "G#3", "B3", "E4"], label: "E7", beats: 2 },
        { notes: ["A2", "E3", "A3", "C#4", "E4"], label: "A", beats: 2 },
        { notes: ["G2", "B2", "D3", "G3", "B3", "F4"], label: "G7", beats: 2 },
        { notes: ["C3", "E3", "G3", "C4", "E4"], label: "C", beats: 2 },
        { notes: ["B2", "D#3", "A3", "B3", "F#4"], label: "B7", beats: 2 },
        { notes: ["E2", "B2", "E3", "G3", "B3", "E4"], label: "Em", beats: 2 },
      ],
    },
  ],

  "shw-gtr-changes": [
    {
      type: "guitar-chord",
      label: "C - fingers 1 and 2 stay for Am",
      frets: [null, 3, 2, 0, 1, 0],
      fingers: [null, 3, 2, null, 1, null],
    },
    {
      type: "guitar-chord",
      label: "Am - only finger 3 moved",
      frets: [null, 0, 2, 2, 1, 0],
      fingers: [null, null, 2, 3, 1, null],
    },
    {
      type: "sequence",
      label: "Change every 4 beats: C to G at 80 bpm",
      instrument: "guitar",
      bpm: 80,
      steps: [
        { notes: ["C3", "E3", "G3", "C4", "E4"], label: "C" },
        { notes: ["C3", "E3", "G3", "C4", "E4"] },
        { notes: ["C3", "E3", "G3", "C4", "E4"] },
        { notes: ["C3", "E3", "G3", "C4", "E4"] },
        { notes: ["G2", "B2", "D3", "G3", "B3", "G4"], label: "G" },
        { notes: ["G2", "B2", "D3", "G3", "B3", "G4"] },
        { notes: ["G2", "B2", "D3", "G3", "B3", "G4"] },
        { notes: ["G2", "B2", "D3", "G3", "B3", "G4"] },
      ],
    },
    {
      type: "sequence",
      label: "Am to E - same shape, shifted one string",
      instrument: "guitar",
      bpm: 70,
      steps: [
        { notes: ["A2", "E3", "A3", "C4", "E4"], label: "Am", beats: 2 },
        { notes: ["E2", "B2", "E3", "G#3", "B3", "E4"], label: "E", beats: 2 },
        { notes: ["A2", "E3", "A3", "C4", "E4"], label: "Am", beats: 2 },
        { notes: ["E2", "B2", "E3", "G#3", "B3", "E4"], label: "E", beats: 2 },
      ],
    },
  ],

  "shw-gtr-tab": [
    {
      type: "fretboard",
      label: "The riff's notes - all on the low E string",
      notes: [
        { string: 6, fret: 0, label: "0", root: true },
        { string: 6, fret: 3, label: "3" },
        { string: 6, fret: 5, label: "5" },
        { string: 6, fret: 6, label: "6" },
      ],
      startFret: 0,
      fretCount: 7,
    },
    {
      type: "sequence",
      label: "Play it: 0-3-5, 0-3-6-5",
      instrument: "guitar",
      bpm: 90,
      steps: [
        { notes: ["E2"], label: "0" },
        { notes: ["G2"], label: "3" },
        { notes: ["A2"], label: "5", beats: 2 },
        { notes: ["E2"], label: "0" },
        { notes: ["G2"], label: "3" },
        { notes: ["Bb2"], label: "6" },
        { notes: ["A2"], label: "5", beats: 2 },
      ],
    },
  ],

  "shw-gtr-first-songs": [
    {
      type: "sequence",
      label: "Three-chord song skeleton: G - C - D - G",
      instrument: "guitar",
      bpm: 80,
      steps: [
        { notes: ["G2", "B2", "D3", "G3", "B3", "G4"], label: "G", beats: 4 },
        { notes: ["C3", "E3", "G3", "C4", "E4"], label: "C", beats: 4 },
        { notes: ["D3", "A3", "D4", "F#4"], label: "D", beats: 4 },
        { notes: ["G2", "B2", "D3", "G3", "B3", "G4"], label: "G", beats: 4 },
      ],
    },
    {
      type: "sequence",
      label: "Four-chord loop: G - Em - C - D",
      instrument: "guitar",
      bpm: 80,
      steps: [
        { notes: ["G2", "B2", "D3", "G3", "B3", "G4"], label: "G", beats: 4 },
        { notes: ["E2", "B2", "E3", "G3", "B3", "E4"], label: "Em", beats: 4 },
        { notes: ["C3", "E3", "G3", "C4", "E4"], label: "C", beats: 4 },
        { notes: ["D3", "A3", "D4", "F#4"], label: "D", beats: 4 },
      ],
    },
  ],

  "shw-pno-hands-together": [
    {
      type: "piano",
      label: "C position, both hands",
      notes: ["C3", "D3", "E3", "F3", "G3", "C4", "D4", "E4", "F4", "G4"],
      roots: ["C3", "C4"],
    },
    {
      type: "sequence",
      label: "Both hands, same rhythm - octaves",
      instrument: "piano",
      bpm: 70,
      steps: [
        { notes: ["C3", "C4"], label: "C" },
        { notes: ["D3", "D4"], label: "D" },
        { notes: ["E3", "E4"], label: "E" },
        { notes: ["F3", "F4"], label: "F" },
        { notes: ["G3", "G4"], label: "G", beats: 2 },
        { notes: ["E3", "E4"], label: "E" },
        { notes: ["C3", "C4"], label: "C", beats: 2 },
      ],
    },
    {
      type: "sequence",
      label: "Melody over left-hand block chords",
      instrument: "piano",
      bpm: 70,
      steps: [
        { notes: ["C3", "E3", "G3", "E4"], label: "C + melody" },
        { notes: ["F4"] },
        { notes: ["G4"] },
        { notes: ["E4"] },
        { notes: ["G2", "B2", "D3", "F4"], label: "G7" },
        { notes: ["E4"] },
        { notes: ["D4"] },
        { notes: ["C3", "E3", "G3", "C4"], label: "C", beats: 2 },
      ],
    },
  ],

  "shw-pno-easy-scales": [
    {
      type: "piano",
      label: "C major scale keys",
      notes: ["C4", "D4", "E4", "F4", "G4", "A4", "B4", "C5"],
      roots: ["C4", "C5"],
    },
    {
      type: "sequence",
      label: "C major, right hand: thumb under after 3",
      instrument: "piano",
      bpm: 70,
      steps: [
        { notes: ["C4"], label: "1" },
        { notes: ["D4"], label: "2" },
        { notes: ["E4"], label: "3" },
        { notes: ["F4"], label: "1" },
        { notes: ["G4"], label: "2" },
        { notes: ["A4"], label: "3" },
        { notes: ["B4"], label: "4" },
        { notes: ["C5"], label: "5" },
      ],
    },
    {
      type: "sequence",
      label: "G major - same fingering, one sharp",
      instrument: "piano",
      bpm: 70,
      steps: [
        { notes: ["G3"], label: "1" },
        { notes: ["A3"], label: "2" },
        { notes: ["B3"], label: "3" },
        { notes: ["C4"], label: "1" },
        { notes: ["D4"], label: "2" },
        { notes: ["E4"], label: "3" },
        { notes: ["F#4"], label: "4" },
        { notes: ["G4"], label: "5" },
      ],
    },
    {
      type: "sequence",
      label: "F major - the odd one out (no thumb on Bb)",
      instrument: "piano",
      bpm: 70,
      steps: [
        { notes: ["F4"], label: "1" },
        { notes: ["G4"], label: "2" },
        { notes: ["A4"], label: "3" },
        { notes: ["Bb4"], label: "4" },
        { notes: ["C5"], label: "1" },
        { notes: ["D5"], label: "2" },
        { notes: ["E5"], label: "3" },
        { notes: ["F5"], label: "4" },
      ],
    },
  ],

  "shw-pno-accompaniment": [
    {
      type: "sequence",
      label: "Broken triads: C - F - G - C",
      instrument: "piano",
      bpm: 90,
      steps: [
        { notes: ["C3"], label: "C" },
        { notes: ["E3"] },
        { notes: ["G3"] },
        { notes: ["E3"] },
        { notes: ["F3"], label: "F" },
        { notes: ["A3"] },
        { notes: ["C4"] },
        { notes: ["A3"] },
        { notes: ["G3"], label: "G" },
        { notes: ["B3"] },
        { notes: ["D4"] },
        { notes: ["B3"] },
        { notes: ["C3"], label: "C" },
        { notes: ["E3"] },
        { notes: ["G3"] },
        { notes: ["E3"] },
      ],
    },
    {
      type: "sequence",
      label: "Root - fifth - octave",
      instrument: "piano",
      bpm: 80,
      steps: [
        { notes: ["C3"], label: "root" },
        { notes: ["G3"], label: "fifth" },
        { notes: ["C4"], label: "octave" },
        { notes: ["G3"], label: "fifth" },
        { notes: ["G2"], label: "root" },
        { notes: ["D3"], label: "fifth" },
        { notes: ["G3"], label: "octave" },
        { notes: ["D3"], label: "fifth" },
      ],
    },
    {
      type: "sequence",
      label: "Waltz bass: root, chord, chord",
      instrument: "piano",
      bpm: 100,
      steps: [
        { notes: ["C3"], label: "C" },
        { notes: ["E3", "G3"], label: "chord" },
        { notes: ["E3", "G3"], label: "chord" },
        { notes: ["G2"], label: "G" },
        { notes: ["B2", "D3"], label: "chord" },
        { notes: ["B2", "D3"], label: "chord" },
      ],
    },
  ],

  "shw-pno-first-songs": [
    {
      type: "sequence",
      label: "Verse loop: C - Am - F - G, block chords",
      instrument: "piano",
      bpm: 80,
      steps: [
        { notes: ["C3", "E3", "G3"], label: "C", beats: 4 },
        { notes: ["A2", "C3", "E3"], label: "Am", beats: 4 },
        { notes: ["F2", "A2", "C3"], label: "F", beats: 4 },
        { notes: ["G2", "B2", "D3"], label: "G", beats: 4 },
      ],
    },
    {
      type: "sequence",
      label: "Same loop with a broken-triad left hand",
      instrument: "piano",
      bpm: 90,
      steps: [
        { notes: ["C3"], label: "C" },
        { notes: ["E3"] },
        { notes: ["G3"] },
        { notes: ["E3"] },
        { notes: ["A2"], label: "Am" },
        { notes: ["C3"] },
        { notes: ["E3"] },
        { notes: ["C3"] },
        { notes: ["F2"], label: "F" },
        { notes: ["A2"] },
        { notes: ["C3"] },
        { notes: ["A2"] },
        { notes: ["G2"], label: "G" },
        { notes: ["B2"] },
        { notes: ["D3"] },
        { notes: ["B2"] },
      ],
    },
  ],
};
