import type { Visual } from "./types";

/**
 * Interactive visuals for the "surface" tier (depth 1).
 * Keyed by topic id; every topic in the tier has at least one visual.
 */
export const SURFACE_VISUALS: Record<string, Visual[]> = {
  "srf-note-names": [
    {
      type: "piano",
      label: "The seven naturals: C D E F G A B",
      notes: ["C4", "D4", "E4", "F4", "G4", "A4", "B4"],
      roots: ["C4"],
      startOctave: 4,
      octaves: 1,
    },
    {
      type: "sequence",
      label: "The 12-note chromatic climb, C to C",
      instrument: "piano",
      bpm: 80,
      steps: [
        { notes: ["C4"], label: "C" },
        { notes: ["C#4"], label: "C#/Db" },
        { notes: ["D4"], label: "D" },
        { notes: ["D#4"], label: "D#/Eb" },
        { notes: ["E4"], label: "E" },
        { notes: ["F4"], label: "F" },
        { notes: ["F#4"], label: "F#/Gb" },
        { notes: ["G4"], label: "G" },
        { notes: ["G#4"], label: "G#/Ab" },
        { notes: ["A4"], label: "A" },
        { notes: ["A#4"], label: "A#/Bb" },
        { notes: ["B4"], label: "B" },
        { notes: ["C5"], label: "C", beats: 2 },
      ],
    },
    {
      type: "fretboard",
      label: "Half steps on the low E string: one fret = one half step",
      notes: [
        { string: 6, fret: 0, label: "E", root: true },
        { string: 6, fret: 1, label: "F" },
        { string: 6, fret: 2, label: "F#" },
        { string: 6, fret: 3, label: "G" },
        { string: 6, fret: 4, label: "G#" },
        { string: 6, fret: 5, label: "A" },
      ],
      startFret: 0,
      fretCount: 5,
    },
  ],

  "srf-rhythm-counting": [
    {
      type: "sequence",
      label: "Quarter notes: count 1 2 3 4",
      instrument: "piano",
      bpm: 80,
      steps: [
        { notes: ["C3"], label: "1" },
        { notes: ["C3"], label: "2" },
        { notes: ["C3"], label: "3" },
        { notes: ["C3"], label: "4" },
      ],
    },
    {
      type: "sequence",
      label: "Eighth notes: count 1 & 2 & 3 & 4 &",
      instrument: "piano",
      bpm: 80,
      steps: [
        { notes: ["C3"], label: "1", beats: 0.5 },
        { notes: ["C3"], label: "&", beats: 0.5 },
        { notes: ["C3"], label: "2", beats: 0.5 },
        { notes: ["C3"], label: "&", beats: 0.5 },
        { notes: ["C3"], label: "3", beats: 0.5 },
        { notes: ["C3"], label: "&", beats: 0.5 },
        { notes: ["C3"], label: "4", beats: 0.5 },
        { notes: ["C3"], label: "&", beats: 0.5 },
      ],
    },
    {
      type: "sequence",
      label: "Rests are notes too: play on 1 and 3, silence on 2 and 4",
      instrument: "piano",
      bpm: 80,
      steps: [
        { notes: ["C3"], label: "1" },
        { notes: [], label: "(2)" },
        { notes: ["C3"], label: "3" },
        { notes: [], label: "(4)" },
        { notes: ["C3"], label: "1" },
        { notes: [], label: "(2)" },
        { notes: ["C3"], label: "3" },
        { notes: [], label: "(4)" },
      ],
    },
  ],

  "srf-chord-charts": [
    {
      type: "sequence",
      label: "A four-bar chart on guitar: G / C / D / G, one bar each",
      instrument: "guitar",
      bpm: 90,
      steps: [
        { notes: ["G2", "B2", "D3", "G3", "B3", "G4"], label: "G", beats: 4 },
        { notes: ["C3", "E3", "G3", "C4", "E4"], label: "C", beats: 4 },
        { notes: ["D3", "A3", "D4", "F#4"], label: "D", beats: 4 },
        { notes: ["G2", "B2", "D3", "G3", "B3", "G4"], label: "G", beats: 4 },
      ],
    },
    {
      type: "sequence",
      label: "The same chart on piano: the symbols mean the same everywhere",
      instrument: "piano",
      bpm: 90,
      steps: [
        { notes: ["G3", "B3", "D4"], label: "G", beats: 4 },
        { notes: ["C4", "E4", "G4"], label: "C", beats: 4 },
        { notes: ["D4", "F#4", "A4"], label: "D", beats: 4 },
        { notes: ["G3", "B3", "D4"], label: "G", beats: 4 },
      ],
    },
  ],

  "srf-gtr-anatomy": [
    {
      type: "fretboard",
      label: "The six open strings: E A D G B E (low to high)",
      notes: [
        { string: 6, fret: 0, label: "E", root: true },
        { string: 5, fret: 0, label: "A" },
        { string: 4, fret: 0, label: "D" },
        { string: 3, fret: 0, label: "G" },
        { string: 2, fret: 0, label: "B" },
        { string: 1, fret: 0, label: "E", root: true },
      ],
      startFret: 0,
      fretCount: 5,
    },
    {
      type: "sequence",
      label: "Tuning check: play each open string, low to high",
      instrument: "guitar",
      bpm: 60,
      steps: [
        { notes: ["E2"], label: "E (6th)" },
        { notes: ["A2"], label: "A (5th)" },
        { notes: ["D3"], label: "D (4th)" },
        { notes: ["G3"], label: "G (3rd)" },
        { notes: ["B3"], label: "B (2nd)" },
        { notes: ["E4"], label: "E (1st)" },
      ],
    },
  ],

  "srf-gtr-fretting": [
    {
      type: "fretboard",
      label: "One finger per fret on the B string (press just behind the fret)",
      notes: [
        { string: 2, fret: 1, label: "1" },
        { string: 2, fret: 2, label: "2" },
        { string: 2, fret: 3, label: "3" },
        { string: 2, fret: 4, label: "4" },
      ],
      startFret: 0,
      fretCount: 5,
    },
    {
      type: "sequence",
      label: "The 1-2-3-4 climb: every note should ring clean",
      instrument: "guitar",
      bpm: 70,
      steps: [
        { notes: ["C4"], label: "1" },
        { notes: ["C#4"], label: "2" },
        { notes: ["D4"], label: "3" },
        { notes: ["D#4"], label: "4" },
        { notes: ["D4"], label: "3" },
        { notes: ["C#4"], label: "2" },
        { notes: ["C4"], label: "1", beats: 2 },
      ],
    },
  ],

  "srf-gtr-open-chords": [
    {
      type: "guitar-chord",
      label: "E major",
      frets: [0, 2, 2, 1, 0, 0],
      fingers: [null, 2, 3, 1, null, null],
    },
    {
      type: "guitar-chord",
      label: "A major",
      frets: [null, 0, 2, 2, 2, 0],
    },
    {
      type: "guitar-chord",
      label: "D major",
      frets: [null, null, 0, 2, 3, 2],
      fingers: [null, null, null, 1, 3, 2],
    },
    {
      type: "guitar-chord",
      label: "G major",
      frets: [3, 2, 0, 0, 0, 3],
    },
    {
      type: "guitar-chord",
      label: "C major",
      frets: [null, 3, 2, 0, 1, 0],
      fingers: [null, 3, 2, null, 1, null],
    },
  ],

  "srf-gtr-strumming": [
    {
      type: "sequence",
      label: "Four downstrums on E: one per beat",
      instrument: "guitar",
      bpm: 80,
      steps: [
        { notes: ["E2", "B2", "E3", "G#3", "B3", "E4"], label: "1 D" },
        { notes: ["E2", "B2", "E3", "G#3", "B3", "E4"], label: "2 D" },
        { notes: ["E2", "B2", "E3", "G#3", "B3", "E4"], label: "3 D" },
        { notes: ["E2", "B2", "E3", "G#3", "B3", "E4"], label: "4 D" },
      ],
    },
    {
      type: "sequence",
      label: "D-DU-UDU on E: the arm never stops (silent on the gaps)",
      instrument: "guitar",
      bpm: 80,
      steps: [
        { notes: ["E2", "B2", "E3", "G#3", "B3", "E4"], label: "1 D", beats: 0.5 },
        { notes: [], label: "&", beats: 0.5 },
        { notes: ["E2", "B2", "E3", "G#3", "B3", "E4"], label: "2 D", beats: 0.5 },
        { notes: ["E2", "B2", "E3", "G#3", "B3", "E4"], label: "& U", beats: 0.5 },
        { notes: [], label: "3", beats: 0.5 },
        { notes: ["E2", "B2", "E3", "G#3", "B3", "E4"], label: "& U", beats: 0.5 },
        { notes: ["E2", "B2", "E3", "G#3", "B3", "E4"], label: "4 D", beats: 0.5 },
        { notes: ["E2", "B2", "E3", "G#3", "B3", "E4"], label: "& U", beats: 0.5 },
      ],
    },
  ],

  "srf-pno-geography": [
    {
      type: "piano",
      label: "Every C sits just left of the two black keys",
      notes: ["C3", "C4", "C5"],
      roots: ["C3", "C4", "C5"],
      startOctave: 3,
      octaves: 3,
    },
    {
      type: "piano",
      label: "One octave of white keys, middle C to the next C",
      notes: ["C4", "D4", "E4", "F4", "G4", "A4", "B4", "C5"],
      roots: ["C4", "C5"],
      startOctave: 4,
      octaves: 2,
    },
    {
      type: "sequence",
      label: "Walk one octave and land on the next C",
      instrument: "piano",
      bpm: 90,
      steps: [
        { notes: ["C4"], label: "C" },
        { notes: ["D4"], label: "D" },
        { notes: ["E4"], label: "E" },
        { notes: ["F4"], label: "F" },
        { notes: ["G4"], label: "G" },
        { notes: ["A4"], label: "A" },
        { notes: ["B4"], label: "B" },
        { notes: ["C5"], label: "C", beats: 2 },
      ],
    },
  ],

  "srf-pno-posture": [
    {
      type: "piano",
      label: "Five-finger (C) position: thumb on C, one finger per key",
      notes: ["C4", "D4", "E4", "F4", "G4"],
      roots: ["C4"],
      startOctave: 4,
      octaves: 1,
    },
    {
      type: "sequence",
      label: "Five-finger pattern, up and back, relaxed hand",
      instrument: "piano",
      bpm: 80,
      steps: [
        { notes: ["C4"], label: "1" },
        { notes: ["D4"], label: "2" },
        { notes: ["E4"], label: "3" },
        { notes: ["F4"], label: "4" },
        { notes: ["G4"], label: "5" },
        { notes: ["F4"], label: "4" },
        { notes: ["E4"], label: "3" },
        { notes: ["D4"], label: "2" },
        { notes: ["C4"], label: "1", beats: 2 },
      ],
    },
  ],

  "srf-pno-triads": [
    {
      type: "piano",
      label: "C major triad: C E G",
      notes: ["C4", "E4", "G4"],
      roots: ["C4"],
      startOctave: 4,
      octaves: 2,
    },
    {
      type: "piano",
      label: "F major triad: F A C",
      notes: ["F4", "A4", "C5"],
      roots: ["F4"],
      startOctave: 4,
      octaves: 2,
    },
    {
      type: "piano",
      label: "G major triad: G B D",
      notes: ["G4", "B4", "D5"],
      roots: ["G4"],
      startOctave: 4,
      octaves: 2,
    },
    {
      type: "sequence",
      label: "Switching in time: C -> F -> G -> C",
      instrument: "piano",
      bpm: 70,
      steps: [
        { notes: ["C4", "E4", "G4"], label: "C", beats: 2 },
        { notes: ["F4", "A4", "C5"], label: "F", beats: 2 },
        { notes: ["G4", "B4", "D5"], label: "G", beats: 2 },
        { notes: ["C4", "E4", "G4"], label: "C", beats: 2 },
      ],
    },
  ],

  "srf-pno-melody": [
    {
      type: "sequence",
      label: "Ode to Joy (opening) in C, right hand alone",
      instrument: "piano",
      bpm: 100,
      steps: [
        { notes: ["E4"], label: "E" },
        { notes: ["E4"], label: "E" },
        { notes: ["F4"], label: "F" },
        { notes: ["G4"], label: "G" },
        { notes: ["G4"], label: "G" },
        { notes: ["F4"], label: "F" },
        { notes: ["E4"], label: "E" },
        { notes: ["D4"], label: "D" },
        { notes: ["C4"], label: "C" },
        { notes: ["C4"], label: "C" },
        { notes: ["D4"], label: "D" },
        { notes: ["E4"], label: "E" },
        { notes: ["E4"], label: "E", beats: 1.5 },
        { notes: ["D4"], label: "D", beats: 0.5 },
        { notes: ["D4"], label: "D", beats: 2 },
      ],
    },
    {
      type: "sequence",
      label: "The same phrase over a held left-hand C",
      instrument: "piano",
      bpm: 100,
      steps: [
        { notes: ["C3", "E4"], label: "C + E" },
        { notes: ["E4"], label: "E" },
        { notes: ["F4"], label: "F" },
        { notes: ["G4"], label: "G" },
        { notes: ["C3", "G4"], label: "C + G" },
        { notes: ["F4"], label: "F" },
        { notes: ["E4"], label: "E" },
        { notes: ["D4"], label: "D" },
      ],
    },
  ],
};
